apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.persistence.volumeSize }}
  storageClassName: {{ $.Values.persistence.storageClass }}